### ISSUE TITLE
'No such file or directory' error

### ISSUE THREAD

**Issue by mherzl** [nix-community/nix-bundle#106]
Most basic usage, i.e. trying to bundle `hello` and run the resulting executable on the same (nixos) system, results in 'No such file or directory' error.

```
$ nix-bundle hello my-hello
Nix bundle created at my-hello.
$ ./my-hello
execvp(/nix/store/fchfx8ykh12d0f8bq0yi3k80mcz7n250-hello-2.12.1my-hello): No such file or directory
```

**Comment by truh** [comment]
nix-bundle.sh TARGET EXECUTABLE

Create a single-file bundle from the nixpkgs attribute "TARGET".

**EXECUTABLE should be relative to the TARGET's output path.**
