### ISSUE TITLE
Is there a way to run bundle when /tmp is noexec

### ISSUE THREAD

**Issue by truh** [nix-community/nix-bundle#108]
When trying to run my htop bundle I get this error

```
.local/bin/htop: line 75: /tmp/tmpx-150dcc3bf43a2fb7/dat/../run: Permission denied
```

`mount` tells me that `/tmp` is mounted with the `noexec` option.

Is there a way to work around such limitations, for example by extracting the bundle in a different location?

**Comment by Artturin** [comment]
https://github.com/nix-community/nix-bundle/pull/111
