### ISSUE TITLE
the nixpkgs checkout is so old that the command fails without `--option deprecated-features url-literals`

### ISSUE THREAD

**Issue by cafkafk** [nix-community/nix-bundle#109]
As the title says, the nixpkgs checkout is so old that the command fails without `--option deprecated-features url-literals`

Consider updating the inputs, and if there isn't a lockfile anyways, may as well go to unstable, perhaps it could avoid this being necessary to fix again. (Ideally, the nixpkgs version would be propagated by e.g. `nixos/bundlers`.

**Comment by Artturin** [comment]
https://github.com/nix-community/nix-bundle/pull/110
