### ISSUE TITLE
Files are placed in /tmp rather than $HOME/.cache

### ISSUE THREAD

**Issue by danieldk** [nix-community/nix-bundle#52]
On top of `default.nix`:

```
let
  arx' = haskellPackages.arx.overrideAttrs (o: {
    patchPhase = (o.patchPhase or "") + ''
      substituteInPlace model-scripts/tmpx.sh \
        --replace /tmp/ \$HOME/.cache/
    '';
  });
```

However, this does not work anymore since: https://github.com/solidsnack/arx/commit/537e1bf57188e772d5eedab44c7ef3da7763817c . On the other hand, passing `--tmpdir '$HOME/.cache'` to `arx` also does not work, since `arx` expects a fully qualified path and thus rejects `$HOME`.

**Comment by Artturin** [comment]
https://github.com/nix-community/nix-bundle/pull/111
