### ISSUE TITLE
`nix bundle` API change

### ISSUE THREAD

**Issue by Radvendii** [nix-community/nix-bundle#88]
In https://github.com/NixOS/nix/pull/5456, the API to `nix bundle` was changed so a bundler should take in a derivation, not a program name. We should update the `nix-bundle` bundler to do that.

Note: I'm not sure if the API change was breaking in the end, or if they retained backward compatibility.

**Comment by Artturin** [comment]
https://github.com/nix-community/nix-bundle/pull/113
